name: CI - Website Tests and Docker Build

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python tests
        run: pytest -v

  docker-build:
    runs-on: ubuntu-latest
    needs: test   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-website website/

      - name: Run Docker container
        run: |
          docker run -d --name my-website-test -p 8080:80 my-website
          # check if container is running
          docker ps -q -f name=my-website-test || exit 1
          docker rm -f my-website-test
